import type { Metadata } from 'next';
import { Geist, Geist_Mono, Quicksand } from 'next/font/google';
import './globals.css';
import { LayoutContainer } from '~/Containers';
import { Header, NavBar } from '~/Components';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const quicksand = Quicksand({
  variable: '--font-quicksand',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Dev Portfolio - Ólafur Ammendrup Ólafsson',
  //description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} ${quicksand.variable} antialiased lg:max-w-[60%]`}>
        <LayoutContainer>
          <NavBar />
          <Header />
          <div className='lg:mx-auto'>
            {children}
          </div>
        </LayoutContainer>
      </body>
    </html>
  );
}
